# Generated by Django 3.0 on 2019-12-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='calculation_time',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tasks',
            name='size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='done',
            field=models.BooleanField(default=True),
        ),
    ]
