# Generated by Django 3.0 on 2019-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('cloud', '0002_auto_20191207_2006')]

    operations = [
        migrations.RemoveField(model_name='tasks', name='id'),
        migrations.AlterField(
            model_name='tasks',
            name='unique_id',
            field=models.CharField(
                blank=True, max_length=100, primary_key=True, serialize=False,
            ),
        ),
    ]
